CREATE TABLE CLIENTES(
    CLIENTE_ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(15),
    DIRECCION NVARCHAR2(40),
    INE NVARCHAR2(10),
    TELEFONO NVARCHAR2(10)
);

Create sequence CLIENTE_SEQ;

CREATE OR REPLACE TRIGGER ON_INSERT_CLIENTE BEFORE
INSERT ON CLIENTES FOR EACH ROW BEGIN
SELECT CLIENTE_SEQ.NEXTVAL INTO :NEW.CLIENTE_ID FROM DUAL;
END;

INSERT ALL
INTO CLIENTES (NOMBRE, DIRECCION, INE, TELEFONO)
VALUES ('Agripino', 'Segoviano', '01455215', '2224356771')
INTO CLIENTES (NOMBRE, DIRECCION, INE, TELEFONO)
VALUES ('Cuesta', 'Caro', '15554852', '222115542')
INTO CLIENTES (NOMBRE, DIRECCION, INE, TELEFONO)
VALUES ('Maduro ', 'Ramirez', '52220213', '2221234567')
SELECT * FROM DUAL;


Select * from clientes;
commit;

DESCRIBE CLIENTES;

