-- 28 de diciembre de 2021

CREATE TABLE ZOOLOGICOS(
    ZOO_ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(20),
    CIUDAD NVARCHAR2(10),
    PAIS NVARCHAR2(10),
    TAMAÑO NUMBER,
    PRESUPUESTO_ANUAL NUMBER    
);

INSERT INTO ZOOLOGICOS (ZOO_ID, NOMBRE, CIUDAD, PAIS, TAMAÑO, PRESUPUESTO_ANUAL)
VALUES (1, 'SAN QUINTIN', 'LA', 'USA', 850, 28000);
SELECT * FROM ZOOLOGICOS;

CREATE TABLE ESPECIE(
    ESPECIE_ID NUMBER PRIMARY KEY,
    NOMBRE_V NVARCHAR2(30),
    NOMBRE_C NVARCHAR2(50),
    FAMILIA NVARCHAR2(30),
    EXTINCION NVARCHAR2(10)
);

INSERT INTO ESPECIE (ESPECIE_ID, NOMBRE_V, NOMBRE_C, FAMILIA, EXTINCION)
VALUES (1, 'GAT0', 'FELINUS DOMESTICUS', 'FELINA', 'NO');
SELECT * FROM ESPECIE;

CREATE TABLE ANIMALES (
    ANIMALES_ID NUMBER PRIMARY KEY,
    ESPECIE_ID NUMBER,
    SEXO NVARCHAR2(10),
    AÑO_NACIMIENTO DATE,
    PAIS NVARCHAR2(30),
    CONTINENTE NVARCHAR2(40)
);

INSERT INTO ANIMALES (ANIMALES_ID, ESPECIE_ID, SEXO, AÑO_NACIMIENTO, PAIS, CONTINENTE)
VALUES(1, '1', 'F', '25-10-2021', 'MEXICO', 'AMERICA');
SELECT * FROM ANIMALES;

CREATE TABLE ZOOS_ANIMALES(
    ZOOS_ANIMALES_ID NUMBER PRIMARY KEY,
    ZOO_ID NUMBER,
    ANIMALES_ID NUMBER
);

INSERT INTO ZOOS_ANIMALES(ZOOS_ANIMALES_ID, ZOO_ID, ANIMALES_ID)
VALUES(1,1,3);

SELECT * FROM ZOOS_ANIMALES;
CREATE TABLE ANIMALES_ESPECIES(
    ANIMALES_ESPECIES_ID NUMBER PRIMARY KEY,
    ESPECIE_ID NUMBER,
    ANIMALES_ID NUMBER
);

INSERT INTO ANIMALES_ESPECIES (ANIMALES_ESPECIES_ID, ESPECIE_ID, ANIMALES_ID )
VALUES (1,1,1);
SELECT * FROM ANIMALES_ESPECIES;


-- CREAR LAS LLAVES FORANEAS

ALTER TABLE ZOOS_ANIMALES ADD CONSTRAINT ZOOS_ANIMALES_FK_ANIMALES
FOREIGN KEY (ANIMALES_ID) REFERENCES ANIMALES(ANIMALES_ID);

ALTER TABLE ZOOS_ANIMALES ADD CONSTRAINT ZOOS_ANIMALES_FK_ZOOLOGICOS
FOREIGN KEY (ZOO_ID) REFERENCES ZOOLOGICOS(ZOO_ID);

ALTER TABLE ANIMALES_ESPECIES ADD CONSTRAINT ANIMALES_ESPECIES_FK_ESPECIE
FOREIGN KEY(ESPECIE_ID) REFERENCES ESPECIE (ESPECIE_ID);

ALTER TABLE ANIMALES_ESPECIES ADD CONSTRAINT  ANIMALES_ESPECIES_FK_ANIMALES
FOREIGN KEY (ANIMALES_ID) REFERENCES ANIMALES (ANIMALES_ID);


--tabla zoologicos
--- CREAMOS UNA SECUENCIA
CREATE SEQUENCE ZOOLOGICOS_SEQ;

--CREAMOS TRIGGERS
CREATE OR REPLACE TRIGGER ON_INSERT_ZOOLOGICOS BEFORE
INSERT ON ZOOLOGICOS FOR EACH ROW BEGIN
SELECT ZOOLOGICOS_SEQ.NEXTVAL INTO :new.ZOO_ID FROM dual;
END;

--tabla especies
--secuencia
CREATE SEQUENCE ESPECIE_SEQ;

-- TRIGGERS
CREATE OR REPLACE TRIGGER ON_INSERT_ESPECIE BEFORE
INSERT ON ESPECIE FOR EACH ROW BEGIN
SELECT ESPECIE_SEQ.NEXTVAL INTO :new.ESPECIE_ID FROM dual;
END;

--TABLA ANIMALES
--SECUENCIA
CREATE SEQUENCE ANIMALES_SEQ;

--TRIGGERS
CREATE OR REPLACE TRIGGER ON_INSERT_ANIMALES BEFORE
INSERT ON ANIMALES FOR EACH ROW BEGIN
SELECT ANIMALES_SEQ.NEXTVAL INTO :new.ANIMALES_ID FROM dual;
END;

--TABLA ZOOS_ANIMALES
CREATE SEQUENCE ZOOS_ANIMALES_SEQ;

--TRIGGERS
CREATE OR REPLACE TRIGGER ON_INSERT_ZOOS_ANIMALES BEFORE
INSERT ON ZOOS_ANIMALES FOR EACH ROW BEGIN
SELECT ZOOS_ANIMALES_SEQ.NEXTVAL INTO :new.ZOOS_ANIMALES_ID FROM dual;
END;

--tabla ANIMALES_ESPECIES
CREATE SEQUENCE ANIMALES_ESPECIES_SEQ;

--TRIGGERS
CREATE OR REPLACE TRIGGER ON_INSERT_ANIMALES_ESPECIES BEFORE
INSERT ON ANIMALES_ESPECIES FOR EACH ROW BEGIN
SELECT ANIMALES_ESPECIES_SEQ.NEXTVAL INTO :new.ANIMALES_ESPECIES_ID FROM dual;
END;


--INSERCION DE REGISTROS USANDO EL TRIGGER Y SECUENCIA
--TABLA ZOOLOGICO
INSERT ALL
INTO ZOOLOGICOS (NOMBRE, CIUDAD, PAIS, TAMAÑO, PRESUPUESTO_ANUAL)
VALUES ('SAN JUANICO', 'LOS SANTOS', 'USA', 1050, 30000)
INTO ZOOLOGICOS (NOMBRE, CIUDAD, PAIS, TAMAÑO, PRESUPUESTO_ANUAL)
VALUES ('SANTA MARTHA', 'ACATITLA', 'MX', 750, 25000)
INTO ZOOLOGICOS (NOMBRE, CIUDAD, PAIS, TAMAÑO, PRESUPUESTO_ANUAL)
VALUES ('SANTA ISABEL', 'MEXICO', 'MX', 1550, 35000)
SELECT * FROM DUAL;

SELECT * FROM ZOOLOGICOS;

--TABLA ESPECIE
INSERT ALL
INTO ESPECIE(NOMBRE_V, NOMBRE_C, FAMILIA, EXTINCION)
VALUES('TIGRE', 'FELINUS', 'FELINA', 'NO')
INTO ESPECIE(NOMBRE_V, NOMBRE_C, FAMILIA, EXTINCION)
VALUES('LEON', 'FELINUS', 'FELINA', 'NO')
INTO ESPECIE(NOMBRE_V, NOMBRE_C, FAMILIA, EXTINCION)
VALUES('DIENTES DE SABLE', 'FELINUS', 'FELINA', 'SI')
SELECT * FROM DUAL;

SELECT * FROM ESPECIE;

--TABLA ANIMALES
INSERT ALL 
INTO ANIMALES(ESPECIE_ID, SEXO, AÑO_NACIMIENTO, PAIS, CONTINENTE)
VALUES ('2', 'M', '20-05-2021', 'ESPAÑA', 'EUROPA')
INTO ANIMALES(ESPECIE_ID, SEXO, AÑO_NACIMIENTO, PAIS, CONTINENTE)
VALUES ('3', 'F', '26-10-2021', 'RUSIA', 'EUROPA')
INTO ANIMALES(ESPECIE_ID, SEXO, AÑO_NACIMIENTO, PAIS, CONTINENTE)
VALUES ('4', 'M', '15-05-2021', 'EGIPTO', 'AFRICA')
SELECT * FROM DUAL;

SELECT * FROM ANIMALES;

-- TABLA ZOOS_ANIMALES
INSERT ALL 
INTO ZOOS_ANIMALES(ZOO_ID, ANIMALES_ID)
VALUES(1,2)
INTO ZOOS_ANIMALES(ZOO_ID, ANIMALES_ID)
VALUES(2,2)
INTO ZOOS_ANIMALES(ZOO_ID, ANIMALES_ID)
VALUES(3,3)
INTO ZOOS_ANIMALES(ZOO_ID, ANIMALES_ID)
VALUES(4,4)
SELECT * FROM DUAL;

SELECT * FROM ZOOS_ANIMALES;

-- TABLA ANIMALES_ESPECIES
INSERT ALL 
INTO ANIMALES_ESPECIES(ESPECIE_ID, ANIMALES_ID)
VALUES(2,2)
INTO ANIMALES_ESPECIES(ESPECIE_ID, ANIMALES_ID)
VALUES(3,3)
INTO ANIMALES_ESPECIES(ESPECIE_ID, ANIMALES_ID)
VALUES(3,4)
SELECT * FROM DUAL;

SELECT * FROM ANIMALES_ESPECIES;




